# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import agent_pb2 as proto_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnderstandIntent = channel.unary_unary(
                '/agent.AIService/UnderstandIntent',
                request_serializer=proto_dot_agent__pb2.IntentRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.IntentResponse.FromString,
                _registered_method=True)
        self.GenerateEmbedding = channel.unary_unary(
                '/agent.AIService/GenerateEmbedding',
                request_serializer=proto_dot_agent__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.GenerateExplanation = channel.unary_unary(
                '/agent.AIService/GenerateExplanation',
                request_serializer=proto_dot_agent__pb2.ExplanationRequest.SerializeToString,
                response_deserializer=proto_dot_agent__pb2.ExplanationResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UnderstandIntent(self, request, context):
        """Understand user intent and extract features
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbedding(self, request, context):
        """Generate text embedding
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateExplanation(self, request, context):
        """Generate recommendation explanation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UnderstandIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.UnderstandIntent,
                    request_deserializer=proto_dot_agent__pb2.IntentRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.IntentResponse.SerializeToString,
            ),
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=proto_dot_agent__pb2.EmbeddingRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.EmbeddingResponse.SerializeToString,
            ),
            'GenerateExplanation': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateExplanation,
                    request_deserializer=proto_dot_agent__pb2.ExplanationRequest.FromString,
                    response_serializer=proto_dot_agent__pb2.ExplanationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UnderstandIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AIService/UnderstandIntent',
            proto_dot_agent__pb2.IntentRequest.SerializeToString,
            proto_dot_agent__pb2.IntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AIService/GenerateEmbedding',
            proto_dot_agent__pb2.EmbeddingRequest.SerializeToString,
            proto_dot_agent__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateExplanation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AIService/GenerateExplanation',
            proto_dot_agent__pb2.ExplanationRequest.SerializeToString,
            proto_dot_agent__pb2.ExplanationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
