# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/agent.proto\x12\x05\x61gent\"@\n\rIntentRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x03(\t\"\xc1\x01\n\x0eIntentResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x35\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32#.agent.IntentResponse.FeaturesEntry\x12\x10\n\x08keywords\x18\x03 \x03(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x17\n\x0fsearch_strategy\x18\x05 \x01(\t\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"9\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x11\n\tdimension\x18\x02 \x01(\x05\"P\n\x08Template\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\"G\n\x12\x45xplanationRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\"\n\ttemplates\x18\x02 \x03(\x0b\x32\x0f.agent.Template\";\n\x13\x45xplanationResponse\x12\x13\n\x0b\x65xplanation\x18\x01 \x01(\t\x12\x0f\n\x07reasons\x18\x02 \x03(\t2\xe2\x01\n\tAIService\x12?\n\x10UnderstandIntent\x12\x14.agent.IntentRequest\x1a\x15.agent.IntentResponse\x12\x46\n\x11GenerateEmbedding\x12\x17.agent.EmbeddingRequest\x1a\x18.agent.EmbeddingResponse\x12L\n\x13GenerateExplanation\x12\x19.agent.ExplanationRequest\x1a\x1a.agent.ExplanationResponseB\x1aZ\x18template-recommend/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030template-recommend/proto'
  _globals['_INTENTRESPONSE_FEATURESENTRY']._loaded_options = None
  _globals['_INTENTRESPONSE_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_INTENTREQUEST']._serialized_start=28
  _globals['_INTENTREQUEST']._serialized_end=92
  _globals['_INTENTRESPONSE']._serialized_start=95
  _globals['_INTENTRESPONSE']._serialized_end=288
  _globals['_INTENTRESPONSE_FEATURESENTRY']._serialized_start=241
  _globals['_INTENTRESPONSE_FEATURESENTRY']._serialized_end=288
  _globals['_EMBEDDINGREQUEST']._serialized_start=290
  _globals['_EMBEDDINGREQUEST']._serialized_end=322
  _globals['_EMBEDDINGRESPONSE']._serialized_start=324
  _globals['_EMBEDDINGRESPONSE']._serialized_end=381
  _globals['_TEMPLATE']._serialized_start=383
  _globals['_TEMPLATE']._serialized_end=463
  _globals['_EXPLANATIONREQUEST']._serialized_start=465
  _globals['_EXPLANATIONREQUEST']._serialized_end=536
  _globals['_EXPLANATIONRESPONSE']._serialized_start=538
  _globals['_EXPLANATIONRESPONSE']._serialized_end=597
  _globals['_AISERVICE']._serialized_start=600
  _globals['_AISERVICE']._serialized_end=826
# @@protoc_insertion_point(module_scope)
